version: '3.7'
services:
    postgres:
        image: postgres:9.6
        container_name: airflow_postgres
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        ports:
            - "5432:5432"
        logging:
            options:
                max-size: 10m
                max-file: "3"

    webserver:
        build: .
        container_name: airflow_webserver
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            # TODO: create a separate schema for real data
            - PG_DB_URL=postgres://airflow:airflow@postgres:5432/airflow
            - AIRFLOW_ROOT_PATH=/usr/local/airflow/
            - DATA_ROOT_PATH=/usr/local/airflow/data
            - GE_PROJECT_PATH=/usr/local/airflow/great_expectations
            - DBT_PROJECT_PATH=/usr/local/airflow/dbt
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ../airflow_dags:/usr/local/airflow/dags
            - ../airflow_data:/usr/local/airflow/data
            - ../great_expectations_projects:/usr/local/airflow/great_expectations
            - ../dbt_project:/usr/local/airflow/dbt
            - ./dbt_pg_profile.yml:/usr/local/airflow/.dbt/profiles.yml
        ports:
            - "8080:8080"
            # - "8888:8888"
            - "8085:8085"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    ge_data_docs:
        image: flashspys/nginx-static
        container_name: ge_data_docs
        ports:
            - 8081:80
        volumes:
            - ~/projects/great_expectations_projects/final/great_expectations/uncommitted/data_docs/local_site:/static
